language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build tinkoff_invest_client.gemspec
  - gem install ./tinkoff_invest_client-1.0.0.gem
