# -*- encoding: utf-8 -*-

=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "tinkoff_invest_client/version"

Gem::Specification.new do |s|
  s.name        = "tinkoff_invest_client"
  s.version     = TinkoffInvestClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Oleg Belov"]
  s.email       = ["al.a.volkov@tinkoff.ru"]
  s.homepage    = "https://github.com/ThinkAndRun/tinkoff_invest_client"
  s.summary     = "Tinkoff Invest OpenAPI Ruby Gem"
  s.description = "tinkoff.ru/invest OpenAPI."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
