=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TinkoffInvestClient::MarketApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MarketApi' do
  before do
    # run before each test
    @api_instance = TinkoffInvestClient::MarketApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketApi' do
    it 'should create an instance of MarketApi' do
      expect(@api_instance).to be_instance_of(TinkoffInvestClient::MarketApi)
    end
  end

  # unit tests for market_bonds_get
  # Получение списка облигаций
  # @param [Hash] opts the optional parameters
  # @return [MarketInstrumentListResponse]
  describe 'market_bonds_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_candles_get
  # Получение исторических свечей по FIGI
  # @param figi FIGI
  # @param from Начало временного промежутка
  # @param to Конец временного промежутка
  # @param interval Интервал свечи
  # @param [Hash] opts the optional parameters
  # @return [CandlesResponse]
  describe 'market_candles_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_currencies_get
  # Получение списка валютных пар
  # @param [Hash] opts the optional parameters
  # @return [MarketInstrumentListResponse]
  describe 'market_currencies_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_etfs_get
  # Получение списка ETF
  # @param [Hash] opts the optional parameters
  # @return [MarketInstrumentListResponse]
  describe 'market_etfs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_orderbook_get
  # Получение стакана по FIGI
  # @param figi FIGI
  # @param depth Глубина стакана [1..20]
  # @param [Hash] opts the optional parameters
  # @return [OrderbookResponse]
  describe 'market_orderbook_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_search_by_figi_get
  # Получение инструмента по FIGI
  # @param figi FIGI
  # @param [Hash] opts the optional parameters
  # @return [SearchMarketInstrumentResponse]
  describe 'market_search_by_figi_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_search_by_ticker_get
  # Получение инструмента по тикеру
  # @param ticker Тикер инструмента
  # @param [Hash] opts the optional parameters
  # @return [MarketInstrumentListResponse]
  describe 'market_search_by_ticker_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for market_stocks_get
  # Получение списка акций
  # @param [Hash] opts the optional parameters
  # @return [MarketInstrumentListResponse]
  describe 'market_stocks_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
