=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TinkoffInvestClient::OperationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OperationsApi' do
  before do
    # run before each test
    @api_instance = TinkoffInvestClient::OperationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OperationsApi' do
    it 'should create an instance of OperationsApi' do
      expect(@api_instance).to be_instance_of(TinkoffInvestClient::OperationsApi)
    end
  end

  # unit tests for operations_get
  # Получение списка операций
  # @param from Начало временного промежутка
  # @param to Конец временного промежутка
  # @param [Hash] opts the optional parameters
  # @option opts [String] :figi Figi инструмента для фильтрации
  # @option opts [String] :broker_account_id Номер счета (по умолчанию - Тинькофф)
  # @return [OperationsResponse]
  describe 'operations_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
