=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TinkoffInvestClient::SandboxApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SandboxApi' do
  before do
    # run before each test
    @api_instance = TinkoffInvestClient::SandboxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SandboxApi' do
    it 'should create an instance of SandboxApi' do
      expect(@api_instance).to be_instance_of(TinkoffInvestClient::SandboxApi)
    end
  end

  # unit tests for sandbox_clear_post
  # Удаление всех позиций
  # Удаление всех позиций клиента
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broker_account_id Номер счета (по умолчанию - Тинькофф)
  # @return [Empty]
  describe 'sandbox_clear_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sandbox_currencies_balance_post
  # Выставление баланса по валютным позициям
  # @param sandbox_set_currency_balance_request Запрос на выставление баланса по валютным позициям
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broker_account_id Номер счета (по умолчанию - Тинькофф)
  # @return [Empty]
  describe 'sandbox_currencies_balance_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sandbox_positions_balance_post
  # Выставление баланса по инструментным позициям
  # @param sandbox_set_position_balance_request Запрос на выставление баланса по инструментным позициям
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broker_account_id Номер счета (по умолчанию - Тинькофф)
  # @return [Empty]
  describe 'sandbox_positions_balance_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sandbox_register_post
  # Регистрация клиента в sandbox
  # Создание счета и валютных позиций для клиента
  # @param [Hash] opts the optional parameters
  # @option opts [SandboxRegisterRequest] :sandbox_register_request Запрос на создание счета и выставление баланса по валютным позициям
  # @return [SandboxRegisterResponse]
  describe 'sandbox_register_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sandbox_remove_post
  # Удаление счета
  # Удаление счета клиента
  # @param [Hash] opts the optional parameters
  # @option opts [String] :broker_account_id Номер счета (по умолчанию - Тинькофф)
  # @return [Empty]
  describe 'sandbox_remove_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
