=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module TinkoffInvestClient
  class CandleResolution
    N1MIN = "1min".freeze
    N2MIN = "2min".freeze
    N3MIN = "3min".freeze
    N5MIN = "5min".freeze
    N10MIN = "10min".freeze
    N15MIN = "15min".freeze
    N30MIN = "30min".freeze
    HOUR = "hour".freeze
    DAY = "day".freeze
    WEEK = "week".freeze
    MONTH = "month".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CandleResolution.constants.select { |c| CandleResolution::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CandleResolution" if constantValues.empty?
      value
    end
  end
end
