=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module TinkoffInvestClient
  class OperationTypeWithCommission
    BUY = "Buy".freeze
    BUY_CARD = "BuyCard".freeze
    SELL = "Sell".freeze
    BROKER_COMMISSION = "BrokerCommission".freeze
    EXCHANGE_COMMISSION = "ExchangeCommission".freeze
    SERVICE_COMMISSION = "ServiceCommission".freeze
    MARGIN_COMMISSION = "MarginCommission".freeze
    OTHER_COMMISSION = "OtherCommission".freeze
    PAY_IN = "PayIn".freeze
    PAY_OUT = "PayOut".freeze
    TAX = "Tax".freeze
    TAX_LUCRE = "TaxLucre".freeze
    TAX_DIVIDEND = "TaxDividend".freeze
    TAX_COUPON = "TaxCoupon".freeze
    TAX_BACK = "TaxBack".freeze
    REPAYMENT = "Repayment".freeze
    PART_REPAYMENT = "PartRepayment".freeze
    COUPON = "Coupon".freeze
    DIVIDEND = "Dividend".freeze
    SECURITY_IN = "SecurityIn".freeze
    SECURITY_OUT = "SecurityOut".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = OperationTypeWithCommission.constants.select { |c| OperationTypeWithCommission::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #OperationTypeWithCommission" if constantValues.empty?
      value
    end
  end
end
