=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module TinkoffInvestClient
  class OperationStatus
    DONE = "Done".freeze
    DECLINE = "Decline".freeze
    PROGRESS = "Progress".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = OperationStatus.constants.select { |c| OperationStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #OperationStatus" if constantValues.empty?
      value
    end
  end
end
