=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module TinkoffInvestClient
  class OrderStatus
    NEW = "New".freeze
    PARTIALLY_FILL = "PartiallyFill".freeze
    FILL = "Fill".freeze
    CANCELLED = "Cancelled".freeze
    REPLACED = "Replaced".freeze
    PENDING_CANCEL = "PendingCancel".freeze
    REJECTED = "Rejected".freeze
    PENDING_REPLACE = "PendingReplace".freeze
    PENDING_NEW = "PendingNew".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = OrderStatus.constants.select { |c| OrderStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #OrderStatus" if constantValues.empty?
      value
    end
  end
end
