=begin
#OpenAPI

#tinkoff.ru/invest OpenAPI.

The version of the OpenAPI document: 1.0.0
Contact: al.a.volkov@tinkoff.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TinkoffInvestClient::OrderType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TinkoffInvestClient::OrderType do
  let(:instance) { TinkoffInvestClient::OrderType.new }

  describe 'test an instance of OrderType' do
    it 'should create an instance of OrderType' do
      expect(instance).to be_instance_of(TinkoffInvestClient::OrderType)
    end
  end
end
